name: Test Pacman

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Try Pacman Generation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output: test.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: pacman-test
          path: test.svg
EOF
